# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hani3K.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_hani3K(object):
    def setupUi(self, hani3K):
        hani3K.setObjectName("hani3K")
        hani3K.resize(692, 524)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(hani3K.sizePolicy().hasHeightForWidth())
        hani3K.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(hani3K)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.book_info = QtWidgets.QTextBrowser(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.book_info.sizePolicy().hasHeightForWidth())
        self.book_info.setSizePolicy(sizePolicy)
        self.book_info.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.book_info.setFont(font)
        self.book_info.setObjectName("book_info")
        self.verticalLayout_10.addWidget(self.book_info)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.word_book = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.word_book.setFont(font)
        self.word_book.setObjectName("word_book")
        self.verticalLayout_4.addWidget(self.word_book)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.load_btn = QtWidgets.QPushButton(self.frame)
        self.load_btn.setObjectName("load_btn")
        self.verticalLayout_4.addWidget(self.load_btn)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.from_bsr = QtWidgets.QLineEdit(self.frame)
        self.from_bsr.setObjectName("from_bsr")
        self.verticalLayout_8.addWidget(self.from_bsr)
        self.to_bsr = QtWidgets.QLineEdit(self.frame)
        self.to_bsr.setObjectName("to_bsr")
        self.verticalLayout_8.addWidget(self.to_bsr)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.learn_type = QtWidgets.QComboBox(self.frame)
        self.learn_type.setObjectName("learn_type")
        self.learn_type.addItem("")
        self.learn_type.addItem("")
        self.learn_type.addItem("")
        self.verticalLayout_6.addWidget(self.learn_type)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)
        self.verticalLayout_10.addLayout(self.verticalLayout_6)
        self.horizontalLayout_3.addWidget(self.frame)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.word_bsr = QtWidgets.QTextBrowser(self.centralwidget)
        self.word_bsr.setObjectName("word_bsr")
        self.verticalLayout_2.addWidget(self.word_bsr)
        self.meaning_bsr = QtWidgets.QTextBrowser(self.centralwidget)
        self.meaning_bsr.setObjectName("meaning_bsr")
        self.verticalLayout_2.addWidget(self.meaning_bsr)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.next_btn = QtWidgets.QPushButton(self.centralwidget)
        self.next_btn.setObjectName("next_btn")
        self.horizontalLayout.addWidget(self.next_btn)
        self.show_btn = QtWidgets.QPushButton(self.centralwidget)
        self.show_btn.setObjectName("show_btn")
        self.horizontalLayout.addWidget(self.show_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.star_btn = QtWidgets.QPushButton(self.centralwidget)
        self.star_btn.setObjectName("star_btn")
        self.horizontalLayout_2.addWidget(self.star_btn)
        self.known_btn = QtWidgets.QPushButton(self.centralwidget)
        self.known_btn.setObjectName("known_btn")
        self.horizontalLayout_2.addWidget(self.known_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.log_bsr = QtWidgets.QTextBrowser(self.frame_2)
        self.log_bsr.setObjectName("log_bsr")
        self.verticalLayout_7.addWidget(self.log_bsr)
        self.save_log_btn = QtWidgets.QPushButton(self.frame_2)
        self.save_log_btn.setObjectName("save_log_btn")
        self.verticalLayout_7.addWidget(self.save_log_btn)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        hani3K.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(hani3K)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 692, 22))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        hani3K.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(hani3K)
        self.statusbar.setObjectName("statusbar")
        hani3K.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(hani3K)
        self.load_btn.clicked.connect(hani3K.load_book)
        self.pushButton.clicked.connect(hani3K.start_learn)
        self.save_log_btn.clicked.connect(hani3K.save_log)
        self.next_btn.clicked.connect(hani3K.next_word)
        self.show_btn.clicked.connect(hani3K.show_meaning)
        self.star_btn.clicked.connect(hani3K.star_word)
        self.known_btn.clicked.connect(hani3K.set_known_word)
        self.pushButton_2.clicked.connect(hani3K.use_default)
        QtCore.QMetaObject.connectSlotsByName(hani3K)

    def retranslateUi(self, hani3K):
        _translate = QtCore.QCoreApplication.translate
        hani3K.setWindowTitle(_translate("hani3K", "hani3K"))
        self.label_4.setText(_translate("hani3K", "Word book:"))
        self.pushButton_2.setText(_translate("hani3K", "Use Default"))
        self.load_btn.setText(_translate("hani3K", "Load Book"))
        self.label.setText(_translate("hani3K", "from"))
        self.label_2.setText(_translate("hani3K", "to"))
        self.learn_type.setItemText(0, _translate("hani3K", "All"))
        self.learn_type.setItemText(1, _translate("hani3K", "Star"))
        self.learn_type.setItemText(2, _translate("hani3K", "Unknown"))
        self.pushButton.setText(_translate("hani3K", "Start"))
        self.next_btn.setText(_translate("hani3K", "Next(D)"))
        self.show_btn.setText(_translate("hani3K", "Show(S)"))
        self.star_btn.setText(_translate("hani3K", "Star(W)"))
        self.known_btn.setText(_translate("hani3K", "Known(A)"))
        self.save_log_btn.setText(_translate("hani3K", "Save log"))
        self.menuAbout.setTitle(_translate("hani3K", "About"))

